name: Build Docker images
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build endpoint
        uses: docker/build-push-action@v1
        with:
          push: ${{ github.event_name == 'push' }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: martenseemann/chrome-quic-interop-runner
          tags: latest
          tag_with_ref: true
          add_git_labels: true

